version: '3'
services:
  openface-flask:
    image: mgelisgen/openface-flask:4.0
    build: .
    ports:
      - "80:8000"
    volumes:
      - .:/usr/local/deploy
      - /uploaded
      - /out
      - /dev/null:/usr/local/deploy/output.log
