version: '3'
services:
  openface-flask:
    image: mgelisgen/openface-flask:1.0
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/home/openface-build/deploy
      - /uploaded
      - /out
      - /dev/null:/home/openface-build/deploy/output.log